<?php
if (session_status() === PHP_SESSION_NONE) session_start();
require_once __DIR__.'/config/database.php';
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$token=trim($_GET['token']??$_POST['token']??''); $error=''; $success='';
if (!preg_match('/^[a-f0-9]{64}$/',$token)) $error='Tautan reset password tidak valid.';
$reset=null;
if (!$error) { $stmt=$pdo->prepare("SELECT pr.id,pr.user_id,u.email,u.name FROM password_resets pr INNER JOIN users u ON u.id=pr.user_id WHERE pr.token_hash=:token_hash AND pr.used_at IS NULL AND pr.expires_at>NOW() AND u.status='ACTIVE' LIMIT 1"); $stmt->execute([':token_hash'=>hash('sha256',$token)]); $reset=$stmt->fetch(); if(!$reset)$error='Tautan reset password sudah tidak berlaku.'; }
if ($_SERVER['REQUEST_METHOD']==='POST' && !$error) {
    $password=$_POST['password']??''; $confirm=$_POST['password_confirm']??'';
    if(strlen($password)<8)$error='Password minimal 8 karakter.'; elseif($password!==$confirm)$error='Konfirmasi password tidak sama.'; else { try{$pdo->beginTransaction(); $hash=password_hash($password,PASSWORD_DEFAULT); $stmt=$pdo->prepare("UPDATE users SET password=:password,updated_at=CURRENT_TIMESTAMP WHERE id=:user_id AND status='ACTIVE'");$stmt->execute([':password'=>$hash,':user_id'=>$reset['user_id']]);$stmt=$pdo->prepare("UPDATE password_resets SET used_at=CURRENT_TIMESTAMP WHERE user_id=:reset_user_id AND used_at IS NULL");$stmt->execute([':reset_user_id'=>$reset['user_id']]);$pdo->commit();$success='Password berhasil diubah. Silakan login dengan password baru.';}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Password gagal diubah. Silakan coba lagi.';} } }
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset Password · RE-STOCK</title><link rel="stylesheet" href="/assets/css/app.css"><script src="https://cdn.tailwindcss.com"></script></head><body class="min-h-screen bg-neutral-50 flex items-center justify-center p-4"><div class="w-full max-w-md"><div class="bg-white rounded-3xl border border-neutral-200 p-6 md:p-8 shadow-sm"><div class="mb-7"><div class="text-xs tracking-[.2em] text-neutral-400 font-semibold">RE-STOCK</div><h1 class="text-2xl font-semibold mt-2">Buat Password Baru</h1><p class="text-sm text-neutral-500 mt-2">Password baru minimal 8 karakter.</p></div><?php if($error):?><div class="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="mb-5 rounded-2xl border border-green-200 bg-green-50 p-4 text-sm text-green-700"><?=e($success)?></div><a href="/login.php" class="block text-center rounded-xl bg-neutral-900 text-white py-3 font-medium">Kembali ke Login</a><?php elseif(!$error):?><form method="post" class="space-y-5"><input type="hidden" name="token" value="<?=e($token)?>"><div><label class="block text-sm font-medium text-neutral-700 mb-2">Password Baru</label><input type="password" name="password" minlength="8" required autocomplete="new-password" class="w-full px-4 py-3 rounded-xl border border-neutral-200"></div><div><label class="block text-sm font-medium text-neutral-700 mb-2">Konfirmasi Password</label><input type="password" name="password_confirm" minlength="8" required autocomplete="new-password" class="w-full px-4 py-3 rounded-xl border border-neutral-200"></div><button class="w-full rounded-xl bg-neutral-900 text-white py-3 font-medium">Simpan Password Baru</button></form><?php endif;?></div></div></body></html>
