<?php
require_once '../../../config/database.php';
require_once '../../../includes/auth.php';
if (session_status() === PHP_SESSION_NONE) session_start();
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$ownerId=(int)($authUserId??0); $storeId=(int)($authStoreId??0); $accountId=(int)($authAccountId??0);
if($ownerId<=0||$storeId<=0||$accountId<=0||($authRole??'')!=='ADMIN'){header('Location: /pages/pengaturan/');exit;}
$owner=$pdo->prepare("SELECT su.id FROM store_users su INNER JOIN stores s ON s.id=su.store_id INNER JOIN accounts a ON a.id=s.account_id WHERE su.user_id=:owner_user_id AND su.store_id=:owner_store_id AND su.role='ADMIN' AND su.status='ACTIVE' AND s.status='ACTIVE' AND a.status='ACTIVE' LIMIT 1");
$owner->execute([':owner_user_id'=>$ownerId,':owner_store_id'=>$storeId]); if(!$owner->fetch()){header('Location: /pages/pengaturan/');exit;}
$staffId=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); if(!$staffId||$staffId<=0){header('Location: /pages/pengaturan/staff/');exit;}
$stmt=$pdo->prepare("SELECT u.id,u.name,u.username,u.email,su.status FROM users u INNER JOIN store_users su ON su.user_id=u.id WHERE u.id=:staff_user_id AND su.store_id=:target_store_id AND su.role='STAFF' LIMIT 1");
$stmt->execute([':staff_user_id'=>$staffId,':target_store_id'=>$storeId]); $staff=$stmt->fetch(); if(!$staff){$_SESSION['flash_error']='Staff tidak ditemukan di Store aktif.';header('Location: /pages/pengaturan/staff/');exit;}
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32)); $csrfToken=$_SESSION['csrf_token']; $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrfToken,$_POST['csrf_token']??''))$errors[]='Sesi keamanan tidak valid. Silakan coba lagi.';
 $password=(string)($_POST['password']??''); $confirm=(string)($_POST['password_confirm']??'');
 if($password===''||strlen($password)<8)$errors[]='Password baru minimal 8 karakter.';
 if($password!==$confirm)$errors[]='Konfirmasi password tidak sama.';
 if(!$errors){try{$pdo->beginTransaction();$hash=password_hash($password,PASSWORD_DEFAULT);if(!$hash)throw new RuntimeException('Password hash gagal dibuat.');$q=$pdo->prepare("UPDATE users SET password=:password,updated_at=CURRENT_TIMESTAMP WHERE id=:staff_user_id");$q->execute([':password'=>$hash,':staff_user_id'=>$staffId]);$q=$pdo->prepare("UPDATE password_resets SET used_at=CURRENT_TIMESTAMP WHERE user_id=:staff_user_id AND used_at IS NULL");$q->execute([':staff_user_id'=>$staffId]);$q=$pdo->prepare("INSERT INTO audit_logs (store_id,user_id,action,table_name,record_id,description,created_at) VALUES (:store_id,:owner_id,'UPDATE','users',:record_id,:description,CURRENT_TIMESTAMP)");$q->execute([':store_id'=>$storeId,':owner_id'=>$ownerId,':record_id'=>$staffId,':description'=>'Mereset password Staff dari Pengaturan: '.$staff['name'].' ('.$staff['username'].')']);$pdo->commit();$_SESSION['flash_success']='Password Staff berhasil direset.';header('Location: /pages/pengaturan/staff/');exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$errors[]='Password Staff gagal direset. Silakan coba lagi.';}}
}
$pageTitle='Reset Password Staff'; require_once '../../../includes/header.php'; require_once '../../../includes/sidebar.php';
?>
<main class="main-content"><div class="p-4 md:p-8"><div class="mb-7"><div class="flex items-center gap-2 text-xs text-neutral-400 mb-2"><a href="/pages/pengaturan/">PENGATURAN</a><i data-lucide="chevron-right" class="w-3.5 h-3.5"></i><a href="/pages/pengaturan/staff/">STAFF</a><i data-lucide="chevron-right" class="w-3.5 h-3.5"></i><span>RESET PASSWORD</span></div><h1 class="text-2xl md:text-3xl font-semibold tracking-tight">Reset Password Staff</h1><p class="text-sm text-neutral-500 mt-2">Buat password baru untuk <?=e($staff['name'])?>.</p></div>
<?php if($errors):?><div class="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><?php foreach($errors as $er):?><div>• <?=e($er)?></div><?php endforeach;?></div><?php endif;?>
<div class="max-w-2xl"><form method="post" class="bento-card p-5 md:p-7"><input type="hidden" name="csrf_token" value="<?=e($csrfToken)?>"><div class="rounded-2xl bg-neutral-50 border border-neutral-100 p-4 mb-6"><div class="font-medium"><?=e($staff['name'])?></div><div class="text-sm text-neutral-500 mt-1">@<?=e($staff['username'])?> · <?=e($staff['email']??'')?></div></div><div class="space-y-5"><div><label for="password" class="block text-sm font-medium text-neutral-700 mb-2">Password Baru</label><input type="password" id="password" name="password" minlength="8" required autocomplete="new-password" class="w-full px-4 py-3 rounded-xl border border-neutral-200"></div><div><label for="password_confirm" class="block text-sm font-medium text-neutral-700 mb-2">Konfirmasi Password</label><input type="password" id="password_confirm" name="password_confirm" minlength="8" required autocomplete="new-password" class="w-full px-4 py-3 rounded-xl border border-neutral-200"></div></div><div class="mt-7 pt-5 border-t border-neutral-100 flex flex-col-reverse sm:flex-row sm:justify-end gap-2"><a href="/pages/pengaturan/staff/edit.php?id=<?=(int)$staffId?>" class="inline-flex items-center justify-center px-4 py-3 rounded-xl border border-neutral-200 text-sm font-medium">Batal</a><button class="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-neutral-900 text-white text-sm font-medium"><i data-lucide="key-round" class="w-4 h-4"></i> Simpan Password Baru</button></div></form></div></div></main>
<?php require_once '../../../includes/footer.php'; ?>
